TYPE = 'type'
DELETE_WORD_1 = 'delete'
DELETE_WORD_2 = 'lidl'
DELETE_WORD_3 = 'διαγραφή'
DELETE_WORD_4 = 'elite'
DELETE_LS = [DELETE_WORD_1, DELETE_WORD_2, DELETE_WORD_3, DELETE_WORD_4]
CLICK_1 = 'κλικ'
CLICK_2 = 'click'
CLICK_3 = 'clique'
CLICK_4 = 'lick'
CLICK_5 = 'like'
CLICK_6 = 'league'
CLICK_7 = 'slick'
CLICK_8 = 'λιγκ'
CLICK_9 = 'clic'
CLICK_LS = [CLICK_1, CLICK_2, CLICK_3, CLICK_4, CLICK_5, CLICK_6, CLICK_7, CLICK_8, CLICK_9]
PRESS = 'press'
BACK = 'πίσω'
TYPE = 'type'
OPEN_GRID_1 = 'open'
OPEN_GRID_2 = 'open grid'
OPEN_GRID_3 = 'open greed'
OPEN_GRID_4 = 'open crete'
GRID_OPEN_LS = [OPEN_GRID_1, OPEN_GRID_2, OPEN_GRID_3, OPEN_GRID_4]
CLOSE_GRID_1 = 'close'
CLOSE_GRID_2 = 'close grid'
CLOSE_GRID_3 = 'close greed'
CLOSE_GRID_4 = 'close crete'
GRID_CLOSE_LS = [CLOSE_GRID_1, CLOSE_GRID_2, CLOSE_GRID_3, CLOSE_GRID_4]
NEW_SEARCH = 'νέα αναζήτηση'
THOUSAND_1 = 'χείλια'
THOUSAND_2 = 'κοιλιά'
THOUSAND = '1000'
THOUSAND_LS = [THOUSAND, THOUSAND_1, THOUSAND_2]
DOWN = 'κάτω'
DOWN_2 = 'down'
DOWN_LS = [DOWN, DOWN_2]
UP_1 = 'πάνω'
UP_2 = 'πάνο'
UP_3 = 'up'
UP_LS = [UP_1, UP_2, UP_3]
RIGHT = 'δεξιά'
RIGHT_2 = 'right'
RIGHT_LS = [RIGHT, RIGHT_2]
LEFT = 'αριστερά'
LEFT_2 = 'left'
LEFT_LS = [LEFT, LEFT_2]
SCROLL = 'scroll'
EXIT_1 = 'exit'
EXIT_2 = 'έξοδος'
EXIT_LS = [EXIT_1, EXIT_2]
MESSAGE = 'Please say the term you want to search'